### ISSUE TITLE
Oracle pallet design

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#177]
Currently the oracle pallet of Spacewalk takes the assumption that the host chain will have infrastructure in place (some clients) to feed the oracle pallet with data.

This assumption might be too strong and here I want to evaluate other options.

# General oracle architecture

Generally every (centralized) oracle design for Substrate has the following components:
* an external API that provides price feeds
* some pallet `A` that provides an extrinsic (say `update_price`) to feed price information; usually only certain _authorized_ accounts are allowed to call this extrinsic
* some pallet `B` that stores current prices
  * usually pallet `A` and pallet `B` are identical
  * pallet `B` also provides some API for other pallets to access the stored prices – this usually works via [loose coupling](https://docs.substrate.io/reference/how-to-guides/pallet-design/use-loose-coupling/)
* some client `C` that consumes the external API
* some client `D` that creates transactions for the `update_price` extrinsic, signs them as required (for an _authorized_ account) and submits them to the chain
  * clients `C` and `D` are usually identical, otherwise client `C` provides an API for client `D` to consume

Clients `C` and `D` can be offchain workers, this is particularly suitable for client `D` as it ensures that there is usually one call to the extrinsic `update_price` per block. The offchain workers can be part of either one of the pallets `A`, `B` or yet another pallet. However, it is particularly suitable that it is part of pallet `A` as this is the pallet providing the `update_price` extrinsic.

# Current situation in Spacewalk
In Spacewalk, there is an oracle pallet that has both the functionalities of the pallets `A` and `B`, i.e., it provides the `update_price` extrinsic (called [`feed_values` there](https://github.com/pendulum-chain/spacewalk/blob/bfbe3f1c12581dbbc98541b5fcb0dc89dd90ea6b/pallets/oracle/src/lib.rs#L200)) and it also stores the current prices and makes it available to other pallets.

It requires that the host chain implements the clients `C` and `D` (which can be the same client) in order to feed up to date prices to the extrinsic. In case the host chain wants to implement these clients as offchain workers, it would need to provide another pallet that implements the offchain worker.

# Situation for the DIA oracle pallet
The DIA oracle pallet is a pallet that has the functionalities of pallets `A` and `B` and also comes with an offchain worker that implements client `D`. Furthermore it comes with a client that implements functionality `C` and that is supposed to be deployed colocalized with a collator node. The offchain worker (for `D`) will then feed from the API provided by client `C`.

# General situation in host chains
We can assume that the host chain already contains an oracle pallet similar to the DIA oracle pallet, i.e., a pallet that provides features `A` and `B` – this assumption will for example hold for Amplitude and Pendulum. For that reason the oracle pallet included in Spacewalk adds an additional burden on the host chain as it requires to provide clients `C` and `D`.

A more general approach would be to remove the oracle pallet from Spacewalk and to add an oracle trait (this can, e.g., be an established trait like [`DataProvider`](https://docs.rs/orml-oracle/latest/orml_oracle/trait.DataProvider.html)) and use loose coupling to link to an existing oracle implementation on the host chain.

**Comment by cr4pt0** [comment]
1. Spacewalk oracle pallet has a very important mission to change the status of parachain([security pallet](https://github.com/interlay/interbtc/blob/master/crates/oracle/src/lib.rs#L394-L405)).
2. It is better to not remove spacewalk/oracle pallet. but add dependency `DataProviderExtended` to oracle Config
![5ABA1F7E-961B-4D31-98CA-635B9E7743F2](https://user-images.githubusercontent.com/102041955/211366966-f97c6489-bd70-4d23-868c-905e54c171a6.jpeg)
[orml_oracle::DataProviderExtended](https://docs.rs/orml-oracle/latest/orml_oracle/trait.DataProviderExtended.html) provide access to [TimestampedValue](https://docs.rs/orml-oracle/latest/orml_oracle/module/struct.TimestampedValue.html)

Spacewalk rely on [timestamp](https://github.com/interlay/interbtc/blob/master/crates/oracle/src/lib.rs#L265) for updated prices and [report_oracle_offline](https://github.com/interlay/interbtc/blob/master/crates/oracle/src/lib.rs#L285) to security pallet or [recover_from_oracle_offline](https://github.com/interlay/interbtc/blob/master/crates/oracle/src/lib.rs#L283)

DIA oracle and other oracle providers can implement [DataProviderExtended](https://docs.rs/orml-oracle/latest/orml_oracle/trait.DataProviderExtended.html) trait.
If not it is easy to create a wrapper that will implement DataProviderExtended trait for oracle on host chain and glue all it together.

**Comment by ebma** [comment]
I agree with @cr4pt0 that it might be a good idea to have a 'DataProvider' that implements this `DataProviderExtended` trait in our existing oracle pallet of Spacewalk. Of course, we would then have to implement the 'DataProviderExtended' trait for the DIA oracle. But we would not have to change much about the logic of the current Spacewalk oracle pallet besides removing the logic of feeding values (since that would be taken care of by the Pallet that implements that other trait). And our implementation would be future-proof since it is somewhat agnostic of the actual oracle used on the parachain. 

For that matter, I would suggest that:
- we implement the `DataProviderExtended` trait for the DIA oracle pallet
- we rename the current 'oracle' pallet in Spacewalk to something like 'oracle-extension' (to indicate that this does not have the actual values but provides helper functions)
- we add the new 'DataProvider' type to its `Config`
- we remove the extrinsic for feeding values and respective items from the new 'oracle-extensions' pallet

It's basically like the general approach you suggested @TorstenStueber but we keep some of the required logic of the current oracle pallet around.

**Comment by cr4pt0** [comment]
So. There are few scenarios how to update spacewalk oracle
Keep the code almost the same for compatibility with other spacewalk pallet
Add `DataProvider` type and specify Concrete key -> `OracleKey`
and Concrete value ->  `Self::UnsignedFixedPoint`
```
#[pallet::config]
    pub trait Config:
        frame_system::Config
        + pallet_timestamp::Config
        + security::Config
        + currency::Config<CurrencyId = CurrencyId>
    {
        …
        type DataProvider: DataProviderExtended<OracleKey, TimestampedValue<Self::UnsignedFixedPoint, Self::Moment>>;
    }
```
The codebase of other spacewalk pallets will not change at all.
And we are able ease to configure DataProvider type to load values from existing oracle on host chain.

2. More general solution for spacewalk
Introduce more abstract Pyramid of dependency.
add more configurable type to current spacewalk oracle pallet
```
type Time: Time;
type OracleKey: Parameter + Member;
type OracleValue: Parameter + Member + Ord;
type DataProvider: DataProviderExtended<Self::OracleKey, TimestampedValueOf<Self>>;
```
And it requires  a lot of changes because now there is more concrete dependency in all codebases that refer to concrete `OracleKey:`
```
pub enum Key {
        ExchangeRate(CurrencyId),
        FeeEstimation,
}
```
And Concrete oracle value in currency pallet:
```
type UnsignedFixedPoint: FixedPointNumber<Inner = BalanceOf<Self>>
            + TruncateFixedPointToInt
            + Encode
            + EncodeLike
            + Decode
            + MaybeSerializeDeserialize
            + TypeInfo;
```
I do not a see a reason to go right now with more abstract case  №2
For not it is better go with the first option.
Additionally no mater what option we are going to implement
there will no possible configure DIA oracle to spacewalk oracle without additional wrapper
and convertor  outside of DIA oracle and spacewalk oracle pallet.
We need a convertor to map together a 2 different types of KEY and Values
DIA oracle has a concrete key:
```
pub struct AssetId {
    pub blockchain: Vec<u8>,
    pub symbol: Vec<u8>,
}
```
Spacewalk all codebase has their own other concrete OracleKey
```
pub enum Key {
        ExchangeRate(CurrencyId),
        FeeEstimation,
}
```
DIA oracle has a concrete value type for prices:
```
pub struct CoinInfo {
    pub symbol: SmolStr,
    pub name: SmolStr,
    pub blockchain: SmolStr,
    pub supply: u128,
    pub last_update_timestamp: u64,
    pub price: u128,
}
```
And concrete price type : `u128`
Spacewalk codebase depends on more abstract but still currency pallet associated type
```
type UnsignedFixedPoint: FixedPointNumber<Inner = BalanceOf<Self>>
            + TruncateFixedPointToInt
            + Encode
            + EncodeLike
            + Decode
            + MaybeSerializeDeserialize
            + TypeInfo;
```
So from my point of view we can leave the DIA oracle pallet implementation without additional changes (only include pr from Torsten)
And write additional configuration to glue `dia-oracle` and `spacewalk/oracle-extension` pallet together
with convertor and extend DIA-oracle pallet with correct implementation for DataProviderExtended trait to configure spacewalk/oracle-extension pallet.

**Comment by cr4pt0** [comment]
merged https://github.com/pendulum-chain/spacewalk/pull/187
