### ISSUE TITLE
Use `CreateClaimableBalance` operation when executing redeem requests

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#357]
## Problem 
Accounts on Stellar are inactive until they get created by sending a payment of at least 1 XLM. Inactive accounts can not hold any assets (as they cannot create trustlines to them). When a user creates a new redeem request, they can choose whatever Stellar destination account they want. The problem is that, if the destination account is inactive, the vault cannot send a payment to that account and thus can never fulfill the redeem request. 

## Solution
We can use the '[CreateClaimableBalance](https://developers.stellar.org/docs/encyclopedia/claimable-balances#create-claimable-balance)' operation to 'send' assets to an account even if it is not yet active. Since this is slightly worse UX than using a regular payment operation we should only do this as a fallback when creating a payment would not work.

We should implement the following logic when the vault client is about to create a payment transaction on Stellar for fulfilling a redeem request:
- First fetch the Stellar network for the destination account.  
   - If the request returns 404, the account is inactive 
      - If the to-be-redeemed asset is XLM and the amount is >=1, do the transfer with createAccount operation 
      - Else, fallback to a claimable balance
   - If the request returns account data, check if a trustline to the to-be-redeemed asset exists, (XLM does not need a trustline of course). If that's not the case, fallback to claimable balance
   - else, use a normal payment operation 

### Creating the 'CreateClaimableBalance' operation
The CreateClaimableBalance operation has to match what is expected by [this](https://github.com/pendulum-chain/spacewalk/blob/06873f16c4a7ab884e4759d98b7b86c712e0c0ae/pallets/currency/src/lib.rs#L145) function. Thus, it has to have an '**unconditional**' claim predicate and **exactly one** claimant

**Comment by ebma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/357?planning-poker) with Zenhub @b-yap @TorstenStueber

**Comment by TorstenStueber** [comment]
@ebma There is a race condition here: it could very well be that in between requesting information about the account and sending a transaction conditions of the account change (e.g., the trustline is removed or the account is merged).

Can we reliably detect that a failed transaction fails because of this and no other reason (e.g., I think that we retry to send transactions if they fail because of incorrect sequence numbers, am I right?) and that in this case we would also be able to reliably fall back to claimable balances?

**Comment by TorstenStueber** [comment]
@ebma and @b-yap your estimates are quite different. Is there a misunderstand about this ticket? Can you discuss?

**Comment by b-yap** [comment]
@TorstenStueber  
I've set it to 13 firstly based on my lacking knowledge alone. I haven't done any operation aside from payments. I set it higher because I don't want to take this lightly, as what had happened with the archives issue.

 Secondly is how to test it. More than unit tests I believe. It should be integration tests. There's multiple scenarios Marcel pointed out here:
1.  if account is inactive and asset is xlm but amount >=1
2.  if account is inactive and asset is xlm but amount == 0
3.  if account is inactive and asset is not xlm
4.  if account is active but asset is xlm
5.  if account is active and asset is not xlm but there's no trustline
6.  if account is active and asset is not xlm but there's a trustline

And what part of the code actually to add the changes. 
1. It looks like it's going to be in the [stellar_wallet.rs](https://github.com/pendulum-chain/spacewalk/blob/main/clients/wallet/src/stellar_wallet.rs), since it should be "before" creating the payment transaction. However the file itself is more than 676 lines, so I believe a different file named "operations.rs" to house all current and future operations. In this case, there are 2 additional operations: createaccount() and createclaimablebalance().
2. since this will only cover the redeem request, the checking should be done under [redeem.rs](https://github.com/pendulum-chain/spacewalk/blob/06873f16c4a7ab884e4759d98b7b86c712e0c0ae/clients/vault/src/redeem.rs). 

I do admit I need practice with estimation.  So actually a 5 or 8 would suffice.

**Comment by TorstenStueber** [comment]
@b-yap nothing to admit. No one to blame. There is no right or wrong when it comes to estimation. And the truth is most likely somewhere in between. Great tool to think deeper and this shows me that I might have estimated too low.

I assign this an 8 as it is the average of all of us.

**Comment by ebma** [comment]
> Can we reliably detect that a failed transaction fails because of this and no other reason (e.g., I think that we retry to send transactions if they fail because of incorrect sequence numbers, am I right?) and that in this case we would also be able to reliably fall back to claimable balances?

We can check the error message contained in the `result_codes` item of the response. For example, when trying to send a payment to a Stellar account that does not exist yet, that `result_codes` array would contain an `op_no_destination` IIRC. The list of result codes for 'payment' operations is [here](https://developers.stellar.org/api/errors/result-codes/operation-specific/payment). There also is `op_no_trust` which would be thrown when a trustline is not set. So we can indeed reliably detect why a transaction failed and in that case either retry (eg in case of a sequence number problem) or fall back to a claimable balance. 


My estimation of `3` was probably a bit too low since I did not consider the complexity of the required tests. Not sure if we need to write 'integration tests' or at least I don't think we need to add it to the `vault_integration_tests.rs`, as we don't need to actually fulfill issue/redeem requests on-chain, we just want to check the logic that hopefully can be extracted to some other functions that we then test. I agree with the estimation of `8`.
