### ISSUE TITLE
Update overlay configs and investigate connection issues to overlay network

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#367]
The reason why the connection to the Frankfurt Stellar node failed is that it was migrated and now lives at a new IP address.
We should
- [ ] Re-add the Frankfurt config but change the IP to `85.190.254.217 ` instead, see [here](https://stellarbeat.io/nodes/GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE?center=1).
- [ ] Change the IP of the Singapore config to the IP [here](https://stellarbeat.io/nodes/GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT?center=1)
- [ ] Change the IP of the Iowa config to the IP [here](https://stellarbeat.io/nodes/GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY?center=1)
- [ ] Update all version parameters and the version string to the latest versions shown in [stellarbeat](https://stellarbeat.io/nodes/GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE?center=1&no-scroll=1).
- [ ] Change the history URLs of each config to the respective URL shown in Stellarbeat. Note that each node is supposed to have a different archive URL

### Connection issues

It seems that changing these configuration parameters introduces some other error. The following error is shown when updating the overlay configuration to:

```
# Connection config
{
  "connection_info": {
    "address": "85.190.254.217",
    "port": 11625
  },
  "node_info": {
    "ledger_version": 19,
    "overlay_version": 28,
    "overlay_min_version": 27,
    "version_str": "stellar-core 19.11.0 (7fb6d5e8858fed6ea365f8717b0266635f578477)",
    "is_pub_net": true
  },
  "stellar_history_base_url": "https://stellar-history-de-fra.satoshipay.io/"
}
```

```
# Error shown in vault client logs
Jul 04 09:18:10.503 ERROR stellar_relay_lib::connection::services: Connection timed out after deadline has elapsed seconds
Jul 04 09:18:10.503 ERROR stellar_relay_lib::connection::services: deadline has elapsed for reading messages from Stellar Node. Retry: 0
Jul 04 09:18:49.894 ERROR stellar_relay_lib::connection::services: Connection timed out after deadline has elapsed seconds
Jul 04 09:18:49.894 ERROR stellar_relay_lib::connection::services: deadline has elapsed for reading messages from Stellar Node. Retry: 0
```

Maybe, the error messages shown is not problematic and we can ignore it. But we definitely have to look into this and clarify.

**Comment by pieterjan84** [comment]
Hi! 
FYI I added the hostname of the validators (for example stellar-de-fra.satoshipay.io) on [Stellarbeat](https://stellarbeat.io/nodes/GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT?center=1). This way you don't have to worry about future ip changes. 

That being said, there seems to be a dns issue at the moment with stellar-de-fra.satoshipay.io that should be fixed by satoshipay first :-) You should be able to rely on the hostname because other validators also use these hostnames in their stellar core config. 

Also, https://api.stellarbeat.io/v1 since recently shows the overlay/ledger versions that are used to connect to the stellar network if you want to automate some easy notification.

**Comment by ebma** [comment]
Hey @pieterjan84! Thanks for setting this up and pointing it out. We'll try to fix the DNS configuration now.
