### ISSUE TITLE
Fix issues of connecting to Stellar overlay network on testnet

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk#401]
We are currently facing issues with building consensus proofs for transactions on Stellar's testnet. These problems started after SDF updated their validator nodes to version `20.0.0`. The problem is probably related to the introduction of [GeneralizedTxSet](https://github.com/stellar/stellar-xdr/blob/50e987f9f01d828e72e1640aff9f21e1e172d3f8/Stellar-overlay.x#L260)s to consensus building. 

We need to update our proof-builder to be able to support these new `GeneralizedTxSet`s.

**Comment by ebma** [comment]
@pendulum-chain/product this is the ticket for the problem that we talked about earlier.

**Comment by b-yap** [comment]
@ebma 
I realized that a lot of code should be changed, especially since the hash of a `GeneralizedTransactionSet` is different from a `TransactionSet`. 

The computation found in `stellar-relay` pallet https://github.com/pendulum-chain/spacewalk/blob/31df1832483199b978ae07f6ed4e018a11ff4dba/pallets/stellar-relay/src/lib.rs#L752-L764
is only true for `TransactionSet`. 
I'm divided on where to put the logic of computing the hash of both sets, since I need it for testing purposes inside `stellar-relay-lib`  and production purpose on`stellar-relay` pallet. It looks like duplicate code is inevitable.

https://github.com/pendulum-chain/spacewalk/blob/31df1832483199b978ae07f6ed4e018a11ff4dba/clients/vault/src/oracle/types.rs#L30
^ This has to receive both `TransactionSet` and `GeneralizedTransactionSet`. I will need to do an enum for this. 
Did we ask in `#stellar-core` channel, if mainnet is also going to use `GeneralizedTransactionSet` once it moves to protocol 20? 

That would mean an overall change of the storage:
https://github.com/pendulum-chain/spacewalk/blob/31df1832483199b978ae07f6ed4e018a11ff4dba/clients/vault/src/oracle/storage/impls.rs#L89
Thank goodness we haven't used this yet.

**Comment by b-yap** [comment]
summary from discussion on slack with @ebma :

1. To support both `TransactionSet` and `GeneralizedTransactionSet`, add a prefix here:
https://github.com/pendulum-chain/spacewalk/blob/31df1832483199b978ae07f6ed4e018a11ff4dba/clients/vault/src/oracle/collector/proof_builder.rs#L48
of **_0_** for `TransactionSet` and **_1_** for `GeneralizedTransactionSet`

The Proof must cater to both as well; maybe best to convert it to base64encoded.

**Comment by ebma** [comment]
Sorry, I forgot to reply here. I'll just say it here again for transparency.
Yes it's a good idea to move the code to the `substrate-stellar-sdk`, thanks for doing it as part of [this](https://github.com/pendulum-chain/substrate-stellar-sdk/pull/21).
Yes, mainnet will also use the `GeneralizedTransactionSet` as well, so we need to add logic to handle both. We can do it with the approach of adding prefixes when encoding the data, as you mention [in your comment](https://github.com/pendulum-chain/spacewalk/issues/401#issuecomment-1746935775).

**Comment by prayagd** [comment]
@b-yap looks like this ticket is worked upon, can you please move it to in development if thats the case?

**Comment by annatekl** [comment]
@ebma do we need to check the connection on the mainnet

**Comment by ebma** [comment]
Not really as the Stellar mainnet does not have the Soroban update yet which was the reason we were facing these issues.

**Comment by prayagd** [comment]
@ebma so the stellar mainnet is not going to have update? The question here is do we need additional ticket if the Mainnet update happens or would this fix also work on the Mainnet?

**Comment by ebma** [comment]
> so the stellar mainnet is not going to have update?

It will update but probably only in December.

> The question here is do we need additional ticket if the Mainnet update happens or would this fix also work on the Mainnet?

It will also work on mainnet. The code changes we added are backward-compatible so once we push them in the next runtime upgrade it will work for the current Stellar mainnet as well as once they update their nodes for Soroban. There is no other runtime upgrade needed in December (or whenever they update).
