### ISSUE TITLE
Add `collect` extrinsic to `reward-distribution` pallet

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#407]
This ticket is a part of https://github.com/pendulum-chain/tasks/issues/47

This ticket depends on https://github.com/pendulum-chain/spacewalk/issues/405

Add an extrinsic `collect` (or similar) that takes a the argument `collateral_asset` (a `CurrencyId`) and that allows a signed account id as the origin
  * call `withdraw_reward` of `PooledRewards` where `pool_id` is `collateral_asset`, `stake_id` is the origin, `currency_id` is the native token
  * call `T::Currency::deposit_creating` where `who` is the origin and `value` is the return value of `withdraw_reward`

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk/407?planning-poker) with Zenhub @adelarja @b-yap @ebma @gianfra-t @TorstenStueber

**Comment by gianfra-t** [comment]
If we implement the new `PooledRewards` as it is proposed in [here](https://github.com/pendulum-chain/spacewalk/pull/415), we would have to review the specifics of this issue.

Since `stake_id` will be `vault_id`, the rewards cannot be directly extracted from this pallet just by calling with the `collateral_asset` and the origin. If we would like to maintain the same user level functionality which is to extract all the rewards of a the native `currency_id` (or any reward currency) for any given nominator `account_id` across all vaults it stakes in, we need to store such map (probably in the stake pallet) and iterate through it when the extrinsic is called. 

Alternatively, we could extend this functionality even more so that the user calls without any parameter, and iterate through all the `vault_id` under its control, and for each distribute the rewards for all the `currency_id` distributed in the fees (which would require yet another map).

**Comment by gianfra-t** [comment]
The collect extrinsic has been added on the rewards-pallet in [this](https://github.com/pendulum-chain/spacewalk/pull/415) PR. The extrinsic added allows for the account to withdraw at a given `vault_id` and `reward_currency_id`. 

Although it is not exactly the same functionality stated in the issue, it allows for the proper collection of rewards. I believe that if we don't require an extrinsic that allows to collect all the vault's staked by a given account at the same time, we could close this issue.

**Comment by ebma** [comment]
Closing this ticket now that https://github.com/pendulum-chain/spacewalk/pull/415 is merged.
