### ISSUE TITLE
move redeem logic to appropriate extrinsics in redeem pallet

### ISSUE THREAD

**Issue by ashneverdawn** [pendulum-chain/spacewalk#42]
The logic in the `redeem` extrinsic from the spacewalk pallet needs to be moved into the appropriate extrinsics in the redeem pallet. The appropriate place to put this functionality is `execute_redeem`.

The `redeem` pallet has also the following extrinsics, which need to be left as _Unimplemented_ for the time being:
`request_redeem`, `liquidation_redeem` , `cancel_redeem`, `set_redeem_period`, `mint_tokens_for_reimbursed_redeem`

**Comment by b-yap** [comment]
For the tests, i think I need the `report_stellar_transaction` ... this one perhaps (https://github.com/pendulum-chain/pendulum/issues/22)?

**Comment by gonzamontiel** [comment]
hey @b-yap , for the tests we will need to wait until `dev/include-main-m2-pallets` is ready for testing, but for that we still have some work ahead. In fact this small issues labeled as `merges-to-dev` are intented to slowly put the branch in a testable state. 
I'd consider a successful compilation and a code review enough for merging this one to `dev/include-main-m2-pallets`

**Comment by b-yap** [comment]
@gonzamontiel  Another road block: the Currency. 
 
So the runtime is using the `vault_registry` 's **`CurrencyId`**, and it's used on some configs that I'm hesitant to touch. 
The runtime is also not implementing the `orml-currencies`.
 As much as possible, I'd like to _not_ touch the runtime. 
 
 That means i've placed a _`todo`_ on the redeem config for the following types:
 `Currency`, `StringCurrencyConversion`, `AddressConversion`.
 
 ^ But this would also mess up  inside the `execute_redeem`; instead of _`T::StringConversion`_, I have to access the `StringConversion` struct itself. Not to mention that it's also using spacewalk's  CurrencyId, and not from the config's.

**Comment by ebma** [comment]
Superseded by #92.
